env:
  es6: true
  browser: true
  commonjs: true
  jest: true

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 6
  sourceType: module

parser: "babel-eslint"

plugins: ["react"]

settings:
  react:
    version: "16"
